name: Build POCO F4 Munch KernelSU + SuSFS

on:
  workflow_call:
  workflow_dispatch:

env:
  # Device env
  DEVICE_NAME: "xiaomi"
  DEVICE_CODENAME: "munch"

  CUSTOM_CMDS: "CROSS_COMPILE=aarch64-linux-gnu- CROSS_COMPILE_ARM32=arm-linux-gnueabi-"
  EXTRA_CMDS: "LLVM=1 LLVM_IAS=1"

  KERNEL_SOURCE: "https://github.com/munch-devs/kernel_xiaomi_munch"
  KERNEL_BRANCH: "main"

  CLANG_SOURCE: "https://github.com/bachnxuan/aosp_clang_mirror/releases/download/clang-r563880c-13989888/clang-r563880c.tar.gz"
  CLANG_BRANCH: "main"

  GCC_GNU: false

  DEFCONFIG_SOURCE: ""
  DEFCONFIG_NAME: "munch_defconfig"
  DEFCONFIG_ORIGIN_IMAGE: ""
  DEFCONFIG_FROM_BOOT: false

  PYTHON_VERSION: "3"

  PACK_METHOD: "AnyKernel3"
  PACK_KMODULES: "false"

  KERNELSU_METHOD: "shell"
  KERNELSU_SUS_PATCH: "false"

  PATCHES_SOURCE: ""
  PATCHES_BRANCH: ""

  SUSFS_FOLDER_FIXED: ""
  SUSFS_PATCH_FIXED: ""

  REKERNEL_ENABLE: "false"
  DROIDSPACES_ENABLE: "false"
  NOMOUNT_ENABLE: "true"
  VPNHIDE_ENABLE: "false"

  HOOK_METHOD: "branchlink"
  KERNEL_PATCH: "false"

  KPM_ENABLE: "false"
  KPM_INLINE: "false"
  KPM_KPATCH_NEXT: "false"
